In [388]:
# 또래 지명 응답값 불러오기
import pandas as pd
import requests
from io import BytesIO
url = "https://github.com/Byumin/peer/raw/refs/heads/scoring/point_df.xlsx"
response = requests.get(url)
response.raise_for_status()
df = pd.read_excel(BytesIO(response.content))
df

    point_item_no student_designation student_nomination
0             PN1            student1           student9
1             PN1            student2          student13
2             PN1            student3          student13
3             PN1            student4           student3
4             PN1            student5          student19
..            ...                 ...                ...
375          PN19           student16           student4
376          PN19           student17           student2
377          PN19           student18           student5
378          PN19           student19          student12
379          PN19           student20           student6

[380 rows x 3 columns]

In [389]:
# 자기보고 응답값 불러오기
import pandas as pd
import requests
from io import BytesIO
url = "https://github.com/Byumin/peer/raw/refs/heads/scoring/self_df.xlsx"
response = requests.get(url)
response.raise_for_status()
self_df = pd.read_excel(BytesIO(response.content))
self_df

,students,SR1,SR2,SR3,SR4,SR5,SR6,SR7,SR8,SR9,...,TSR23,TR2,TR3,TR4,TR5,TR6,TR7,TR8,TR9,TR10
0,student1,2,3,3,3,4,4,3,5,4,...,1,2,3,2,3,2,2,4,2,1
1,student2,4,4,2,4,3,3,1,4,3,...,2,3,1,5,3,2,3,1,3,3
2,student3,4,2,3,5,3,1,1,5,3,...,4,3,1,5,1,4,3,1,3,1
3,student4,4,4,1,2,3,5,3,1,5,...,2,1,5,1,3,4,3,5,5,1
4,student5,3,5,3,5,1,4,2,1,4,...,4,1,2,4,4,1,2,1,2,5
5,student6,2,4,2,3,5,4,5,5,4,...,3,4,3,1,2,4,5,4,2,4
6,student7,5,4,2,1,2,2,1,2,3,...,1,3,2,2,3,2,3,3,2,4
7,student8,4,1,3,5,2,5,5,2,3,...,2,2,4,4,3,2,5,4,5,5
8,student9,1,5,1,5,4,3,2,3,2,...,2,3,5,1,1,4,2,2,2,3
9,student10,4,1,2,3,1,3,3,4,1,...,3,5,3,5,4,3,2,1,2,5
10,student11,1,3,4,4,4,5,3,2,2,...,2,4,2,2,5,2,2,5,2,2
11,student12,5,2,4,5,1,4,2,5,4,...,1,4,2,2,2,4,2,4,2,3
12,student13,2,2,4,1,2,4,3,5,2,...,3,1,3,4,3,4,5,3,4,1
13,student14,4,1,5,5,2,2,2,5,2,...,4,3,2,3,2,5,4,2,5,1
14,student15,5,5,5,2,1,3,5,2,1,...,4,2,1,1,3,1,1,3,5,2
15,student16,4,2,5,3,1,1,3,2,1,...,3,2,5,5,5,4,5,3,4,3
16,student17,1,1,1,2,2,2,2,2,2,...,1,5,3,1,2,1,5,5,1,5
17,student18,1,3,2,4,4,5,5,1,3,...,1,3,4,2,1,5,4,2,4,4
18,student19,2,2,2,1,3,5,5,2,5,...,4,5,2,1,2,1,1,3,2,5
19,student20,1,3,4,5,1,4,2,3,4,...,1,5,5,5,1,3,4,3,5,1

## 인포그램 첫번째 페이지  
* 응답값으로 인포그램과 같이 채점 및 시각화

<img src="https://raw.githubusercontent.com/Byumin/peer/scoring/images/report_1.png" width="600" height="300">

In [393]:
# 또래 지명 척도_지각된 인기, 사회적 선호, 외현적 공격성, 관계적 공격성, 친사회성 척도 채점
# 자기보고 척도_인기추구, 인기상실불안 척도 채점
# 해당 척도의 문항 확인
url = "https://github.com/Byumin/peer/raw/refs/heads/item/item_info.xlsx"
response = requests.get(url)
response.raise_for_status()
item = pd.read_excel(BytesIO(response.content))
item = item[item['scale'].str.contains('지각된 인기|사회적 선호|외현적 공격성|관계적 공격성|친사회성|인기추구|인기상실불안', na=False)]
item

    Unnamed: 0    scale     reporting   no                        item reverse
0            0   지각된 인기          또래지명  PN1                   가장 인기가 있는       N
1            1   사회적 선호          또래지명  PN2                 가장 같이 놀고 싶은       N
2            2   사회적 선호          또래지명  PN3                 가장 같이 놀기 싫은       N
3            3  외현적 공격성          또래지명  PN4     문제를 일으키는/학교의 규칙을 지키지 않는       N
4            4  외현적 공격성          또래지명  PN5                      싸움을 하는       N
5            5  관계적 공격성          또래지명  PN6        험담을 하거나 다른 친구를 소외시키는       N
6            6  관계적 공격성          또래지명  PN7                 나쁜 소문을 퍼뜨리는       N
7            7     친사회성          또래지명  PN8                         친절한       N
8            8     친사회성          또래지명  PN9                        협력적인       N
9            9     인기추구  자기보고(5점 리커트)  SR1      나는 인기있는 아이와 친구가 되고 싶다.       N
10          10     인기추구  자기보고(5점 리커트)  SR2         나는 인기있는 무리에 속하고 싶다.       N
11          11     인기추구  자기보고(5점 리커트)  SR3          나는 인기있는 사람이 되고 싶다.       N
12          12   인기상실불안  자기보고(5점 리커트)  SR4  나는 인기없는 아이와는 친구가 되고 싶지 않다.       N
13          13   인기상실불안  자기보고(5점 리커트)  SR5      나는 인기없는 무리에 속하고 싶지 않다.       N
14          14   인기상실불안  자기보고(5점 리커트)  SR6       나는 인기없는 사람이 되고 싶지 않다.       N

### student14 의 인포그램 첫번째 페이지의 점수 산출

In [396]:
# student14의 지각된 인기의 점수 산출
# 활용되는 문항 : PN1

# student14 지명된 횟수
nomination = len(df[(df['point_item_no']=='PN1') & (df['student_nomination']=='student14')])
# 전체 학생 수
total = len(df['student_designation'].unique())
# 지각된 인기 점수
scale_score = round((nomination/total),2)
print('지각된 인기 :', scale_score)

지각된 인기 : 0.05

In [459]:
# 이와 동일하게 사회적 선호 척도 점수 산출
# 활용되는 문항 : PN2, PN3

nomination = len(df[(df['point_item_no']=='PN2') & (df['student_nomination']=='student14')]) + len(df[(df['point_item_no']=='PN3') & (df['student_nomination']=='student14')]) 
total = len(df[df['point_item_no']=='PN2']['student_designation'].unique()) + len(df[df['point_item_no']=='PN3']['student_designation'].unique())
scale_score = round((nomination/total),2)
print('사회적 선호 :', scale_score)

사회적 선호 : 0.07

In [400]:
# 외현적 공격성 척도 점수 산출
# 활용되는 문항 : PN4, PN5

nomination = len(df[(df['point_item_no']=='PN4') & (df['student_nomination']=='student14')]) + len(df[(df['point_item_no']=='PN5') & (df['student_nomination']=='student14')]) 
total = len(df[df['point_item_no']=='PN4']['student_designation'].unique()) + len(df[df['point_item_no']=='PN5']['student_designation'].unique())
scale_score = round((nomination/total),2)
print('외현적 공격성 :', scale_score)

외현적 공격성 : 0.1

In [402]:
# 관계적 공격성 척도 점수 산출
# 활용되는 문항 : PN6, PN7

nomination = len(df[(df['point_item_no']=='PN6') & (df['student_nomination']=='student14')]) + len(df[(df['point_item_no']=='PN7') & (df['student_nomination']=='student14')]) 
total = len(df[df['point_item_no']=='PN6']['student_designation'].unique()) + len(df[df['point_item_no']=='PN7']['student_designation'].unique())
scale_score = round((nomination/total),2)
print('관계적 공격성 :', scale_score)

관계적 공격성 : 0.05

In [404]:
# 친사회성 척도 점수 산출
# 활용되는 문항 : PN8, PN9

nomination = len(df[(df['point_item_no']=='PN8') & (df['student_nomination']=='student14')]) + len(df[(df['point_item_no']=='PN9') & (df['student_nomination']=='student14')]) 
total = len(df[df['point_item_no']=='PN8']['student_designation'].unique()) + len(df[df['point_item_no']=='PN9']['student_designation'].unique())
scale_score = round((nomination/total),2)
print('친사회성 :', scale_score)

친사회성 : 0.07

In [406]:
# 인기추구 척도 점수 산출
# 활용되는 문항 : SR1, SR2, SR3
## 5점 리커트 척도로 점수 산출에 대한 정보가 없음

In [408]:
# 인기상실불안 척도 점수 산출
# 활용되는 문항 : SR4, SR5, SR6
## 5점 리커트 척도로 점수 산출에 대한 정보가 없음

## 인포그램 두번째 페이지  
* 응답값으로 인포그램과 같이 채점 및 시각화

<img src="https://raw.githubusercontent.com/Byumin/peer/scoring/images/report_2.png" width="600" height="300">

In [411]:
# 또래 지명 척도_또래 괴롭힘 가해, 또래 괴롭힘 피해 척도 채점
# 자기보고 척도_인지적 공감, 정서적 공감, 내재화(우울) 척도 채점
# 해당 척도의 문항 확인
url = "https://github.com/Byumin/peer/raw/refs/heads/item/item_info.xlsx"
response = requests.get(url)
response.raise_for_status()
item = pd.read_excel(BytesIO(response.content))
item = item[item['scale'].str.contains('또래 괴롭힘 가해|또래 괴롭힘 피해|인지적 공감|정서적 공감|내재화\(우울\)', na=False)]
item

,Unnamed: 0,scale,reporting,no,item,reverse
15,15,또래 괴롭힘 가해,또래지명,PN10,친구를 괴롭히는 행동을 시작하는,N
16,16,또래 괴롭힘 가해,또래지명,PN11,괴롭힘에 다른 사람을 참여하도록 하는,N
17,17,또래 괴롭힘 피해,또래지명,PN12,다른 아이들에게 자주 놀림을 받는,N
18,18,또래 괴롭힘 피해,또래지명,PN13,다른 아이들에게 맞거나 욕설을 듣는,N
19,19,인지적 공감,자기보고(5점 리커트),SR7,나는 학교에서 나보다 어려운 친구를 보면 걱정되고 마음이 아프다.,N
20,20,인지적 공감,자기보고(5점 리커트),SR8,"가끔은 다른 사람이 어려움을 겪고 있더라도, 나는 그렇게 안타까움이나 미안함을 느끼...",Y
21,21,인지적 공감,자기보고(5점 리커트),SR9,다른 사람을 이용하는 학생과는 친구가 되고 싶지 않다.,N
22,22,인지적 공감,자기보고(5점 리커트),SR10,다른 사람의 불행은 나와는 크게 상관이 없는 일이다.,Y
23,23,인지적 공감,자기보고(5점 리커트),SR11,다른 사람이 불공평한 일을 겪어도 나와 관련 없으면 상관없다.,Y
24,24,인지적 공감,자기보고(5점 리커트),SR12,나는 종종 내가 본 일에 대해 감동받는다.,N
25,25,인지적 공감,자기보고(5점 리커트),SR13,나는 스스로를 마음이 고운 사람이라고 말할 수 있다.,N
26,26,정서적 공감,자기보고(5점 리커트),SR14,내 생각을 정하기 전에 나와 생각이 다른 친구의 의견을 들어보려고 한다.,N
27,27,정서적 공감,자기보고(5점 리커트),SR15,나는 다른 사람의 입장에서 생각하는 것이 어렵다.,Y
28,28,정서적 공감,자기보고(5점 리커트),SR16,"친구를 욕하기 전에, 그 친구 입장에서 생각해본다.",N
29,29,정서적 공감,자기보고(5점 리커트),SR17,"나는 친구들을 더 이해하기 위해서, 친구들의 입장에서 나의 모습이 어떻게 보일지 상...",N
30,30,정서적 공감,자기보고(5점 리커트),SR18,"내가 맞다고 생각되면, 다른 사람의 의견을 듣지 않는다.",Y
31,31,정서적 공감,자기보고(5점 리커트),SR19,"모든 질문은 하나 이상의 답이 있다고 생각하고, 여러 가지 생각을 해본다.",N
32,32,정서적 공감,자기보고(5점 리커트),SR20,화가 났을 때 바로 화내지 않으려 노력한다.,N
33,33,내재화(우울),자기보고(5점 리커트),SR21,평상시에는 아무렇지도 않던 일들이 귀찮게 느껴졌다.,N
34,34,내재화(우울),자기보고(5점 리커트),SR22,무슨 일을 하든 정신을 집중하기가 힘들었다.,N
35,35,내재화(우울),자기보고(5점 리커트),SR23,우울했다.,N
36,36,내재화(우울),자기보고(5점 리커트),SR24,하는 일마다 힘들게 느껴졌다.,N
37,37,내재화(우울),자기보고(5점 리커트),SR25,앞으로 잘 될 것이라고 느꼈다.,Y
38,38,내재화(우울),자기보고(5점 리커트),SR26,두려움을 느꼈다.,N
39,39,내재화(우울),자기보고(5점 리커트),SR27,"잠을 설쳤다, 잠을 잘 이루지 못했다.",N
40,40,내재화(우울),자기보고(5점 리커트),SR28,행복했다.,Y
41,41,내재화(우울),자기보고(5점 리커트),SR29,세상에 홀로 있는 듯 한 외로움을 느꼈다.,N
42,42,내재화(우울),자기보고(5점 리커트),SR30,도무지 무엇을 시작할 기운이 나지 않았다.,N

### student14의 인포그램 두번째 페이지의 점수 산출

In [414]:
# student14의 또래 괴롭힘 가해의 점수 산출
# 활용되는 문항 : PN10, PN11

nomination = len(df[(df['point_item_no']=='PN10') & (df['student_nomination']=='student14')]) + len(df[(df['point_item_no']=='PN11') & (df['student_nomination']=='student14')]) 
total = len(df[df['point_item_no']=='PN10']['student_designation'].unique()) + len(df[df['point_item_no']=='PN11']['student_designation'].unique())
scale_score = round((nomination/total),2)
print('또래 괴롭힘 가해 :', scale_score)

또래 괴롭힘 가해 : 0.03

In [416]:
# student14의 또래 괴롭힘 피해의 점수 산출
# 활용되는 문항 : PN12, PN13

nomination = len(df[(df['point_item_no']=='PN12') & (df['student_nomination']=='student14')]) + len(df[(df['point_item_no']=='PN13') & (df['student_nomination']=='student14')]) 
total = len(df[df['point_item_no']=='PN12']['student_designation'].unique()) + len(df[df['point_item_no']=='PN13']['student_designation'].unique())
scale_score = round((nomination/total),2)
print('또래 괴롭힘 피해 :', scale_score)

또래 괴롭힘 피해 : 0.12

In [418]:
# 인지적 공감 척도 점수 산출
# 활용되는 문항 : SR7, SR8, SR9, SR10, SR11, SR12, SR13
## 5점 리커트 척도로 점수 산출에 대한 정보가 없음

In [420]:
# 정서적 공감 척도 점수 산출
# 활용되는 문항 : SR14, SR15, SR16, SR17, SR18, SR19, SR20
## 5점 리커트 척도로 점수 산출에 대한 정보가 없음

In [422]:
# 내재화(우울) 척도 점수 산출
# 활용되는 문항 : SR21, SR22, SR23, SR24, SR25, SR26, SR27, SR28, SR29, SR30
## 5점 리커트 척도로 점수 산출에 대한 정보가 없음

## 인포그램 세번째 페이지  
* 응답값으로 인포그램과 같이 채점 및 시각화

<img src="https://raw.githubusercontent.com/Byumin/peer/scoring/images/report_3.png" width="600" height="300">

In [425]:
# 자기보고 척도_행동적 참여, 정서적 참여, 협동적 태도, 경쟁적 태도, 교사평정 성취도 척도 채점
# 해당 척도의 문항 확인
url = "https://github.com/Byumin/peer/raw/refs/heads/item/item_info.xlsx"
response = requests.get(url)
response.raise_for_status()
item = pd.read_excel(BytesIO(response.content))
item = item[item['scale'].str.contains('행동적 참여|정서적 참여|협동적 태도|경쟁적 태도|교사평정 성취도', na=False)]
item

,Unnamed: 0,scale,reporting,no,item,reverse
47,47,행동적 참여,자기보고(5점 리커트),SR35,나는 학교에서 잘하려고 노력한다.,N
48,48,행동적 참여,자기보고(5점 리커트),SR36,나는 수업 시간에 최대한 열심히 한다.,N
49,49,행동적 참여,자기보고(5점 리커트),SR37,나는 수업에서 하는 토론에 참여한다.,N
50,50,행동적 참여,자기보고(5점 리커트),SR38,나는 수업에 집중한다.,N
51,51,행동적 참여,자기보고(5점 리커트),SR39,나는 수업을 주의 깊게 듣는다.,N
52,52,정서적 참여,자기보고(5점 리커트),SR40,나는 수업 시간에 기분이 좋다.,N
53,53,정서적 참여,자기보고(5점 리커트),SR41,나는 수업에서 무언가를 할 때 흥미를 느낀다.,N
54,54,정서적 참여,자기보고(5점 리커트),SR42,수업은 재미있다.,N
55,55,정서적 참여,자기보고(5점 리커트),SR43,나는 수업에서 새로운 것을 배우는 것을 즐긴다.,N
56,56,정서적 참여,자기보고(5점 리커트),SR44,나는 수업활동에 적극적으로 참여한다.,N
57,57,협동적 태도,자기보고(5점 리커트),SR45,나는 다른 학생의 학습을 도와주는게 좋다.,N
58,58,협동적 태도,자기보고(5점 리커트),SR46,나는 내 생각이나 준비물을 다른 학생과 공유하는 것을 좋아한다.,N
59,59,협동적 태도,자기보고(5점 리커트),SR47,나는 다른 학생과 협동하는 것을 좋아한다.,N
60,60,협동적 태도,자기보고(5점 리커트),SR48,나는 다른 학생들에게 중요한 것들을 배울 수 있다.,N
61,61,협동적 태도,자기보고(5점 리커트),SR49,모둠 학습에서 내 생각과 준비물을 나누려고 노력한다.,N
62,62,협동적 태도,자기보고(5점 리커트),SR50,학생들은 서로서로 가르쳐주고 배울 수 있다.,N
63,63,협동적 태도,자기보고(5점 리커트),SR51,학습할 때 학생끼리 서로 돕는 것이 좋다고 생각한다. SR52. 나는 다른 학생...,N
64,64,경쟁적 태도,자기보고(5점 리커트),SR53,나는 내가 다른 학생보다 더 좋은 점수를 받기 위해서 공부한다.,N
65,65,경쟁적 태도,자기보고(5점 리커트),SR54,나는 우리 반에서 최고의 학생이 되고 싶다.,N
66,66,경쟁적 태도,자기보고(5점 리커트),SR55,나는 남에게 뒤쳐지는 것을 좋아하지 않는다.,N
67,67,경쟁적 태도,자기보고(5점 리커트),SR56,나는 누가 최고인지 알아보기 위해서 다른 학생과 경쟁(승부를 겨루는 것)하는 것을 ...,N
68,68,경쟁적 태도,자기보고(5점 리커트),SR57,나는 다른 학생과 경쟁(승부를 겨루는 것)할 때 가장 행복하다.,N
69,69,경쟁적 태도,자기보고(5점 리커트),SR58,나는 누가 최고인지 알아보기 위해 도전하는 것을 좋아한다.,N
70,70,경쟁적 태도,자기보고(5점 리커트),SR59,다른 학생과의 경쟁은 공부하기 위한 좋은 방법이다.,N
71,71,교사평정 성취도,자기보고(5점 리커트),TR1,각 학생의 주요과목에 대한 성취도를 평가해주세요.,N

In [427]:
# 행동적 참여 척도 점수 산출
# 활용되는 문항 : SR35, SR36, SR37, SR38, SR39
## 5점 리커트 척도로 점수 산출에 대한 정보가 없음

In [429]:
# 정서적 참여 척도 점수 산출
# 활용되는 문항 : SR40, SR41, SR42, SR43, SR44
## 5점 리커트 척도로 점수 산출에 대한 정보가 없음

In [431]:
# 협동적 태도 척도 점수 산출
# 활용되는 문항 : SR45, SR46, SR47, SR48, SR49, SR50, SR51
## 5점 리커트 척도로 점수 산출에 대한 정보가 없음

In [433]:
# 경쟁적 태도 척도 점수 산출
# 활용되는 문항 : SR52, SR53, SR54, SR55, SR56, SR57, SR58, SR59
## 5점 리커트 척도로 점수 산출에 대한 정보가 없음

In [435]:
# 교사평정 성취도 척도 점수 산출
# 활용되는 문항 : TR1
## 5점 리커트 척도로 점수 산출에 대한 정보가 없음

## 인포그램 네번째 페이지  
* 응답값으로 인포그램과 같이 채점 및 시각화

<img src="https://raw.githubusercontent.com/Byumin/peer/scoring/images/report_4.png" width="600" height="300">

In [438]:
# 또래지명 척도_친한친구, 학습친구, 협동학습 친구, 선망하는 친구, 교사선호, 교사비선호 성취도 척도 채점
# 자기보고 척도_애정, 거부 척도 채점
# 해당 척도의 문항 확인
url = "https://github.com/Byumin/peer/raw/refs/heads/item/item_info.xlsx"
response = requests.get(url)
response.raise_for_status()
item = pd.read_excel(BytesIO(response.content))
item = item[item['scale'].str.contains('친한친구|학습친구|협동학습 친구|선망하는 친구|교사선호|교사비선호|애정|거부', na=False)]
item

,Unnamed: 0,scale,reporting,no,item,reverse
72,72,친한친구,또래지명,PN14,가장 친한 친구는?,N
73,73,학습친구,또래지명,PN15,같이 공부하는 친구는?,N
74,74,협동학습 친구,또래지명,PN16,공부할 때 도움을 요청하는 친구는?,N
75,75,선망하는 친구,또래지명,PN17,"함께 어울리거나, 친구가 되고싶은 사람은?",N
76,76,교사선호,또래지명,PN18,선생님과 잘 지내는,N
77,77,교사비선호,또래지명,PN19,선생님과 잘 지내지 못하는,N
78,78,애정,자기보고(5점 리커트),SR60,부모님은 내가 하고 있는 일들을 중요하게 생각해준다.,N
79,79,애정,자기보고(5점 리커트),SR61,부모님은 내가 착하게 행동하면 칭찬해준다.,N
80,80,애정,자기보고(5점 리커트),SR62,"부모님은 내가 겁을 내거나 당황할 때, 도와주려고 하신다.",N
81,81,애정,자기보고(5점 리커트),SR63,부모님은 내가 칭찬받을 일을 하면 칭찬해주신다.,N
82,82,애정,자기보고(5점 리커트),SR64,부모님은 내가 소중하고 필요한 존재라는 것을 느끼도록 해준다.,N
83,83,애정,자기보고(5점 리커트),SR65,"부모님은 나의 생각들을 존중하고, 내 생각을 표현하도록 북돋아준다.",N
84,84,애정,자기보고(5점 리커트),SR66,"부모님은 일상생활에 관해 나와 같이 이야기하고, 이야기도 들어주신다.",N
85,85,애정,자기보고(5점 리커트),SR67,"부모님은 내가 무언가를 잘했을 때, 나 스스로 자랑스럽게 느끼도록 해준다.",N
86,86,애정,자기보고(5점 리커트),SR68,"부모님은 내가 친구들을 집에 데리고 오는 걸 좋아하고, 친구들에게도 잘해주신다.",N
87,87,거부,자기보고(5점 리커트),SR69,부모님은 나에게 짜증을 낸다.,N
88,88,거부,자기보고(5점 리커트),SR70,부모님은 나를 거칠게 대한다.,N
89,89,거부,자기보고(5점 리커트),SR72,부모님은 내가 잘못하면 바로 혼내신다.,N
90,90,거부,자기보고(5점 리커트),SR72,부모님은 내가 자신을 신경쓰이게 한다고 말하신다.,N
91,91,거부,자기보고(5점 리커트),SR73,부모님은 나의 기분을 상하게 한다.,N
92,92,거부,자기보고(5점 리커트),SR74,"부모님은 내가 잘못을 저지를 경우, 윽박지르거나 위협적으로 대한다.",N
93,93,거부,자기보고(5점 리커트),SR75,부모님은 화가 났을 때 나를 심하게 혼낸다.,N

In [440]:
# student14의 친한친구의 점수 산출
# 활용되는 문항 : PN14

nomination = len(df[(df['point_item_no']=='PN14') & (df['student_nomination']=='student14')])
print('친한친구 :', nomination)

친한친구 : 2

In [442]:
# student14의 학습친구의 점수 산출
# 활용되는 문항 : PN15

nomination = len(df[(df['point_item_no']=='PN15') & (df['student_nomination']=='student14')])
print('학습친구 :', nomination)

학습친구 : 0

In [444]:
# student14의 협동학습의 점수 산출
# 활용되는 문항 : PN16

nomination = len(df[(df['point_item_no']=='PN16') & (df['student_nomination']=='student14')])
print('협동학습친구 :', nomination)

협동학습친구 : 2

In [446]:
# student14의 선망하는 친구의 점수 산출
# 활용되는 문항 : PN17

nomination = len(df[(df['point_item_no']=='PN17') & (df['student_nomination']=='student14')])
print('선망하는 친구 :', nomination)

선망하는 친구 : 0

In [448]:
# student14의 교사선호의 점수 산출
# 활용되는 문항 : PN18

nomination = len(df[(df['point_item_no']=='PN18') & (df['student_nomination']=='student14')])
print('교사선호 :', nomination)

교사선호 : 4

In [450]:
# student14의 선망하는 친구의 점수 산출
# 활용되는 문항 : PN19

nomination = len(df[(df['point_item_no']=='PN19') & (df['student_nomination']=='student14')])
print('교사비선호 :', nomination)

교사비선호 : 0

In [341]:
# 애정 척도 점수 산출
# 활용되는 문항 : SR60, SR61, SR62, SR63, SR64, SR65, SR66, SR67, SR68
## 평균점수 산출이 맞는지 확인이 필요함
self_df.loc[self_df['students']=='student14',]

,students,SR1,SR2,SR3,SR4,SR5,SR6,SR7,SR8,SR9,...,TSR23,TR2,TR3,TR4,TR5,TR6,TR7,TR8,TR9,TR10
8,student9,1,5,1,5,4,3,2,3,2,...,2,3,5,1,1,4,2,2,2,3

In [331]:
self_df

,students,SR1,SR2,SR3,SR4,SR5,SR6,SR7,SR8,SR9,...,TSR23,TR2,TR3,TR4,TR5,TR6,TR7,TR8,TR9,TR10
0,student1,2,3,3,3,4,4,3,5,4,...,1,2,3,2,3,2,2,4,2,1
1,student2,4,4,2,4,3,3,1,4,3,...,2,3,1,5,3,2,3,1,3,3
2,student3,4,2,3,5,3,1,1,5,3,...,4,3,1,5,1,4,3,1,3,1
3,student4,4,4,1,2,3,5,3,1,5,...,2,1,5,1,3,4,3,5,5,1
4,student5,3,5,3,5,1,4,2,1,4,...,4,1,2,4,4,1,2,1,2,5
5,student6,2,4,2,3,5,4,5,5,4,...,3,4,3,1,2,4,5,4,2,4
6,student7,5,4,2,1,2,2,1,2,3,...,1,3,2,2,3,2,3,3,2,4
7,student8,4,1,3,5,2,5,5,2,3,...,2,2,4,4,3,2,5,4,5,5
8,student9,1,5,1,5,4,3,2,3,2,...,2,3,5,1,1,4,2,2,2,3
9,student10,4,1,2,3,1,3,3,4,1,...,3,5,3,5,4,3,2,1,2,5
10,student11,1,3,4,4,4,5,3,2,2,...,2,4,2,2,5,2,2,5,2,2
11,student12,5,2,4,5,1,4,2,5,4,...,1,4,2,2,2,4,2,4,2,3
12,student13,2,2,4,1,2,4,3,5,2,...,3,1,3,4,3,4,5,3,4,1
13,student14,4,1,5,5,2,2,2,5,2,...,4,3,2,3,2,5,4,2,5,1
14,student15,5,5,5,2,1,3,5,2,1,...,4,2,1,1,3,1,1,3,5,2
15,student16,4,2,5,3,1,1,3,2,1,...,3,2,5,5,5,4,5,3,4,3
16,student17,1,1,1,2,2,2,2,2,2,...,1,5,3,1,2,1,5,5,1,5
17,student18,1,3,2,4,4,5,5,1,3,...,1,3,4,2,1,5,4,2,4,4
18,student19,2,2,2,1,3,5,5,2,5,...,4,5,2,1,2,1,1,3,2,5
19,student20,1,3,4,5,1,4,2,3,4,...,1,5,5,5,1,3,4,3,5,1

In [325]:
# 거부 척도 점수 산출
# 활용되는 문항 : SR69, SR70, SR71, SR72, SR73, SR74, SR75
## 평균점수 산출이 맞는지 확인이 필요함

In [339]:
# 일곱번째 페이지에서
# 왼쪽 꺽은선 그래프에서 교사 점수를 어떻게 산출하는지 모르겠음
# TR2, TR3, TR4, TR5, TR6, TR7, TR8, TR9, TR10 에서
# TR2 인기
# TR3 사회적 산호
# TR4 공격성(??)외현적
# TR5 공격성(??관계적
# TR6 괴롭힘 가해
# TR7 괴롭힘 피해
# TR8가 친사회성
# TR9 행동적 수업참여
# TR10 정서적 수업참여

# 이걸로 평가한다면 5점 만점 척도로 학생들을 평가하는 것
# 학생들은 또래지명 값으로 점수가 나옴
# 왼쪽 꺽은선 그래프에선 학생의 경우

In [ ]:
# 자기보고와 또래지명 사이의 scale range 문제가 있음
# 이걸 어떻게 해야할지 논의가 필요함